on: [ push, pull_request ]
name: Lint
jobs:
  static-check:
    if: 'false' # Skip until 1.18 supported
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.41
