on:
  schedule:
  - cron: '30 19 * * *'
name: Nightly
jobs:
  monkey-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [race-monkey-test, race-ondisk-monkey-test, memfs-monkey-test, memfs-ondisk-monkey-test]
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Test
      env:
        TARGET: ${{ matrix.target }}
      run: |
        git clone https://github.com/lni/drummer
        cd drummer
        go get github.com/coufalja/tugboat@master
        make test
        make $TARGET
