on: [push, pull_request]
name: Test
jobs:
  unit-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
       make actions-test
  arm64-unit-test:
    runs-on: self-hosted
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test
  race-unit-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: RACE=1 make test
  memfs-unit-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: MEMFS_TEST=1 make test
  macos-unit-test:
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test
  windows-unit-test:
    runs-on: windows-latest
    steps:
     - name: Install Go
       uses: actions/setup-go@v2
       with:
         go-version: 1.17.x
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Test
       run: go test -v
  build-tools:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: make tools
  static-check:
    runs-on: ubuntu-18.04
    steps:
     - name: Install Go
       uses: actions/setup-go@v2
       with:
         go-version: 1.17.x
     - name: Install golangci-lint
       run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -s -- -b $GOROOT/bin v1.23.8
        go get -u github.com/kisielk/errcheck
        go get -u golang.org/x/lint/golint
        go get -u github.com/gordonklaus/ineffassign
        sudo apt-get install librocksdb-dev
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Static check
       run: make static-check
