on: [ push, pull_request ]
name: Test
jobs:
  unit-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.18.0-beta1'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        make actions-test
  race-unit-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.18.0-beta1'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: RACE=1 make test
  macos-unit-test:
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.18.0-beta1'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test
  windows-unit-test:
    runs-on: windows-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.18.0-beta1'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v
